import type { Handler } from '@netlify/functions';
import { registerUser, authenticate, sessionFrom, userStore, type User, type Role } from './_auth';
import { deliveryStore, type DeliveryRecord, type DeliveryStatus } from './_store';
const json=(statusCode:number,body:unknown)=>({statusCode,headers:{'Content-Type':'application/json','Cache-Control':'no-store'},body:JSON.stringify(body)});
const safe=(u:User)=>{const {passwordHash,...rest}=u;return rest};
const getDeliveries=async()=>{const list=await deliveryStore().list({prefix:'NOMAD-',limit:500});const out:any[]=[];for(const key of list.blobs||[]){const d=await deliveryStore().get(key.key,{type:'json'}) as any;if(d)out.push(d)}return out.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))};
const saveUser=async(u:User)=>{const s=userStore();await s.setJSON(u.id,u);await s.setJSON('phone:'+u.phone,u);if(u.email)await s.setJSON('email:'+u.email,u)};
const saveDelivery=async(d:DeliveryRecord)=>{d.updatedAt=new Date().toISOString();await deliveryStore().setJSON(d.ref,d);return d};
export const handler:Handler=async event=>{try{const body=JSON.parse(event.body||'{}');const action=String(body.action||'');
if(event.httpMethod==='POST'&&action==='register'){const requestedRole:Role=body.role==='RIDER'?'RIDER':'CUSTOMER';const u=await registerUser({...body,role:requestedRole});const auth=await authenticate(body.phone,body.password);return json(201,{ok:true,user:safe(u),token:auth.token})}
if(event.httpMethod==='POST'&&action==='login'){const a=await authenticate(String(body.login||''),String(body.password||''));return json(200,{ok:true,user:safe(a.user),token:a.token})}
const session=await sessionFrom(event);if(!session)return json(401,{error:'Please sign in'});
if(action==='me')return json(200,{ok:true,user:safe(session.user)});if(action==='logout')return json(200,{ok:true});
if(action==='deliveries'){const all=await getDeliveries();if(session.role==='CUSTOMER')return json(200,{ok:true,deliveries:all.filter(d=>d.customerId===session.user.id||d.senderPhone===session.user.phone)});if(session.role==='RIDER')return json(200,{ok:true,deliveries:all.filter(d=>d.riderId===session.user.id||(!d.riderId&&d.status==='ORDER RECEIVED'))});return json(200,{ok:true,deliveries:all})}
if(action==='rider-status'&&session.role==='RIDER'){const u=await userStore().get(session.user.id,{type:'json'}) as User;if(typeof body.online==='boolean')u.online=body.online;u.updatedAt=new Date().toISOString();await saveUser(u);return json(200,{ok:true,user:safe(u)})}
if(action==='rider-accept'&&session.role==='RIDER'){const d=await deliveryStore().get(String(body.ref||'').toUpperCase(),{type:'json'}) as DeliveryRecord|null;if(!d)return json(404,{error:'Delivery not found'});if(!session.user.approved)return json(403,{error:'Rider approval required'});if(d.riderId||d.status!=='ORDER RECEIVED')return json(409,{error:'Job is no longer available'});d.riderId=session.user.id;d.riderName=session.user.name;d.riderPhone=session.user.phone;d.status='RIDER ASSIGNED';d.acceptedAt=new Date().toISOString();return json(200,{ok:true,delivery:await saveDelivery(d)})}
if(action==='rider-update'&&session.role==='RIDER'){const d=await deliveryStore().get(String(body.ref||'').toUpperCase(),{type:'json'}) as DeliveryRecord|null;const status=body.status as DeliveryStatus;if(!d)return json(404,{error:'Delivery not found'});if(d.riderId!==session.user.id)return json(403,{error:'This job is not assigned to you'});if(!(['COLLECTED','OUT FOR DELIVERY'] as string[]).includes(status))return json(400,{error:'Invalid rider status'});if(d.status==='RIDER ASSIGNED'&&status!=='COLLECTED')return json(400,{error:'Collect the package first'});if(d.status==='COLLECTED'&&status!=='OUT FOR DELIVERY')return json(400,{error:'Invalid status transition'});d.status=status;if(status==='COLLECTED')d.collectedAt=new Date().toISOString();return json(200,{ok:true,delivery:await saveDelivery(d)})}
if(action==='verify-pin'&&session.role==='RIDER'){const d=await deliveryStore().get(String(body.ref||'').toUpperCase(),{type:'json'}) as DeliveryRecord|null;if(!d)return json(404,{error:'Delivery not found'});if(d.riderId!==session.user.id)return json(403,{error:'This job is not assigned to you'});if(d.status!=='OUT FOR DELIVERY')return json(400,{error:'Delivery must be out for delivery'});if(String(body.pin||'')!==d.pin)return json(400,{error:'Incorrect receiver PIN'});d.status='DELIVERED';d.deliveredAt=new Date().toISOString();return json(200,{ok:true,delivery:await saveDelivery(d)})}
if(action==='admin-assign'&&session.role==='ADMIN'){const d=await deliveryStore().get(String(body.ref||'').toUpperCase(),{type:'json'}) as DeliveryRecord|null;const rider=await userStore().get(String(body.riderId||''),{type:'json'}) as User|null;if(!d||!rider||rider.role!=='RIDER'||!rider.approved)return json(400,{error:'Valid approved rider required'});if(d.status==='DELIVERED')return json(400,{error:'Delivery is already complete'});d.riderId=rider.id;d.riderName=rider.name;d.riderPhone=rider.phone;d.status='RIDER ASSIGNED';d.acceptedAt=d.acceptedAt||new Date().toISOString();return json(200,{ok:true,delivery:await saveDelivery(d)})}
if(action==='admin-status'&&session.role==='ADMIN'){const d=await deliveryStore().get(String(body.ref||'').toUpperCase(),{type:'json'}) as DeliveryRecord|null;const status=body.status as DeliveryStatus;if(!d)return json(404,{error:'Delivery not found'});if(!['ORDER RECEIVED','RIDER ASSIGNED','COLLECTED','OUT FOR DELIVERY','DELIVERED'].includes(status))return json(400,{error:'Invalid status'});d.status=status;if(status==='DELIVERED')d.deliveredAt=new Date().toISOString();return json(200,{ok:true,delivery:await saveDelivery(d)})}
if(action==='admin-data'&&session.role==='ADMIN'){const users:any[]=[];for(const x of (await userStore().list({prefix:'user_',limit:500})).blobs||[]){const u=await userStore().get(x.key,{type:'json'});if(u)users.push(safe(u as User))}const deliveries=await getDeliveries();const riders=users.filter(u=>u.role==='RIDER'),customers=users.filter(u=>u.role==='CUSTOMER');return json(200,{ok:true,summary:{customers:customers.length,riders:riders.length,pendingRiders:riders.filter(r=>!r.approved).length,onlineRiders:riders.filter(r=>r.approved&&r.online).length,activeDeliveries:deliveries.filter(d=>d.status!=='DELIVERED').length,completedDeliveries:deliveries.filter(d=>d.status==='DELIVERED').length},riders,customers,deliveries})}
if(action==='admin-approve'&&session.role==='ADMIN'){const u=await userStore().get(String(body.userId||''),{type:'json'}) as User|null;if(!u||u.role!=='RIDER')return json(404,{error:'Rider not found'});u.approved=Boolean(body.approved);u.updatedAt=new Date().toISOString();await saveUser(u);return json(200,{ok:true,user:safe(u)})}
if(action==='rider-earnings'&&session.role==='RIDER'){const all=await getDeliveries();const completed=all.filter(d=>d.riderId===session.user.id&&d.status==='DELIVERED');const earnings=completed.reduce((n,d)=>n+(Number(d.charge)||0),0);return json(200,{ok:true,completed,earnings})}
return json(400,{error:'Unknown action'})}catch(e:any){return json(400,{error:e?.message||'Request failed'})}};