import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{Bike,Package,ShoppingBag,MapPin,Clock,ShieldCheck,ChevronRight,MessageCircle,Menu,X,ArrowRight}from'lucide-react';import'./styles.css';

type Module='rent'|'send'|'fetch'|null;

const services=[{id:'rent' as const,icon:Bike,title:'RENT',headline:'Move your way.',text:'Reliable bikes and scooters for a few hours, a day, or longer.',cta:'Rent a Bike'},{id:'send' as const,icon:Package,title:'SEND',headline:'Send it. We move it.',text:'Local parcel pickup and delivery for people, hotels, shops and businesses.',cta:'Send a Package'},{id:'fetch' as const,icon:ShoppingBag,title:'FETCH',headline:'Need it? We fetch it.',text:'Tell us what you need from a local shop, market or partner and we deliver.',cta:'Request an Errand'}];

function App(){const[module,setModule]=useState<Module>(null);const[menu,setMenu]=useState(false);
return <div className="app">
<header><a className="logo" href="#"><span>A.</span>NOMAD <small>BIKES</small></a><nav className={menu?'open':''}><a href="#services" onClick={()=>setMenu(false)}>Services</a><a href="#how" onClick={()=>setMenu(false)}>How it works</a><a href="#areas" onClick={()=>setMenu(false)}>Areas</a><a href="#business" onClick={()=>setMenu(false)}>Business</a><button className="lang">EN ▾</button></nav><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>

<main>
<section className="hero"><div className="hero-copy"><p className="eyebrow">WATAMU · MALINDI · COASTAL KENYA</p><h1>MOVE<br/><em>YOUR WAY.</em></h1><p className="lead">Mobility and local logistics built for the coast. Rent a bike, send a package, or get what you need — without the hassle.</p><div className="hero-actions"><button className="primary" onClick={()=>setModule('rent')}>Rent a Bike <ArrowRight/></button><button className="ghost" onClick={()=>setModule('send')}>Send a Package</button></div></div><div className="hero-card"><div className="route"><span>01</span><div><b>WATAMU</b><small>Start anywhere</small></div></div><div className="route-line"></div><div className="route"><span>02</span><div><b>MALINDI</b><small>We'll get it there</small></div></div><div className="coast">A.NOMAD<br/><strong>COASTAL MOBILITY</strong></div></div></section>

<section id="services" className="section"><div className="section-head"><div><p className="eyebrow">ONE PLATFORM</p><h2>Rent. Send. <em>Fetch.</em></h2></div><p>One local platform for everyday movement and logistics across coastal Kenya.</p></div><div className="service-grid">{services.map(s=><article className="service" key={s.id}><div className="service-icon"><s.icon/></div><span className="number">0{services.indexOf(s)+1}</span><h3>{s.title}</h3><h4>{s.headline}</h4><p>{s.text}</p><button onClick={()=>setModule(s.id)}>{s.cta}<ChevronRight/></button></article>)}</div></section>

<section id="how" className="dark section"><div className="section-head"><div><p className="eyebrow">SIMPLE BY DESIGN</p><h2>How it <em>works.</em></h2></div></div><div className="steps"><div><span>01</span><h3>Choose</h3><p>Pick a bike, send a parcel, or tell us what you need.</p></div><div><span>02</span><h3>Book</h3><p>Give us the details, timing and pickup or delivery point.</p></div><div><span>03</span><h3>Move</h3><p>We confirm the job and keep you updated through completion.</p></div></div></section>

<section id="areas" className="section areas"><div><p className="eyebrow">WHERE WE MOVE</p><h2>Made for the <em>coast.</em></h2><p className="area-copy">Starting in Watamu and Malindi, with service coverage expanding across coastal Kenya.</p></div><div className="area-list"><span>Watamu</span><span>Malindi</span><span>Matsangoni</span><span>Kilifi</span><span>Mombasa</span><span>More coming</span></div></section>

<section id="business" className="business"><div><p className="eyebrow">FOR BUSINESS</p><h2>Your local<br/><em>logistics partner.</em></h2><p>Hotels, villas, restaurants, shops, offices and tour operators can use A.NOMAD for recurring deliveries, guest mobility and everyday errands.</p><button className="primary" onClick={()=>setModule('send')}>Talk to A.NOMAD <ArrowRight/></button></div><div className="business-points"><p><ShieldCheck/> Verified operations</p><p><Clock/> Scheduled & on-demand</p><p><MapPin/> Local coastal coverage</p></div></section>

<section className="trust section"><div><p className="eyebrow">BUILT AROUND YOU</p><h2>Local service.<br/><em>Smart platform.</em></h2></div><div className="trust-grid"><div><ShieldCheck/><b>Safety & verification</b><p>Clear booking details, customer information and operational checks.</p></div><div><MessageCircle/><b>Easy support</b><p>Quick communication through WhatsApp and direct customer support.</p></div><div><MapPin/><b>Coastal first</b><p>Designed around how people and businesses actually move here.</p></div></div></section>
</main>

<footer><div><a className="logo" href="#"><span>A.</span>NOMAD <small>BIKES</small></a><p>Mobility & Local Logistics</p></div><div className="footer-links"><a href="#">Terms</a><a href="#">Privacy</a><a href="#">Safety</a><a href="https://wa.me/254700000000">WhatsApp</a></div><small>© 2026 A.NOMAD BIKES LIMITED</small></footer>

{module&&<div className="modal-backdrop" onClick={()=>setModule(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModule(null)}><X/></button><p className="eyebrow">A.NOMAD {module.toUpperCase()}</p><h2>{module==='rent'?'Rent a Bike':module==='send'?'Send a Package':'Request an Errand'}</h2><p>Tell us what you need. The full booking flow will be connected here next.</p><label>Your name<input placeholder="Full name"/></label><label>Phone number<input placeholder="+254"/></label><label>{module==='rent'?'Pickup location':'Pickup / shop location'}<input placeholder="Watamu, Malindi or nearby"/></label><button className="primary full" onClick={()=>setModule(null)}>Continue <ArrowRight/></button></div></div>}
</div>}
createRoot(document.getElementById('root')!).render(<App/>);